services:
  db:
    image: mysql:9.0
    container_name: db
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
